### ISSUE TITLE
Bug: Fragments are not working (Unknown Fragment error)

### ISSUE THREAD

**Issue by arsinclair** [WalltoWall/gatsby-plugin-imgix#8]
Hey there,

`...GatsbyImgixFluid` and other fragments are not working in user _graphql_ code because fragment definitions are commented out in the code of the plugin.

I believe either fragments should be uncommented, or the docs must change to exclude them. Currently both README.md and docs at gatsbyjs website say that the fragments can be used and give examples of the usage.

**Comment by angeloashmore** [comment]
Hi @arsinclair, you're right, they're commented out temporarily until the fields are properly set up with a GraphQL Interface.

In the mean time, you can copy the fragments into your project.

**Comment by arsinclair** [comment]
@angeloashmore, they have been commented out for 7 months now. Maybe the documentation should be updated? Cause currently it should be treated as a bug - docs show how to use it, but it doesn't work that way.

I suggest we either remove fragments from the docs completely, or explicitly mention that fragments should be defined by the end user.
It can spare between few minutes to a few hours of troubleshooting time for people who haven't used the plugin before.

**Comment by angeloashmore** [comment]
@arsinclair `v0.9.0` fixes the fragments. Can you give it a try?

**Comment by angeloashmore** [comment]
I'm going to close this issue but feel free to reply if something is still not working correctly. Thanks!

**Comment by arsinclair** [comment]
@angeloashmore everything seem to be working well! Thanks for great work!
